# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-17 20:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundperson',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='FoundPersonImage',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='MissingPersonImage',
            field=models.FileField(upload_to=''),
        ),
    ]
